Develop
bchronowski98/todo-app-better pull request #4
Opened 2022-11-02 10:19 UTC by bchronowski98

2022-11-03 11:59 UTC, pyotrr requested changes

2022-11-03 11:59 UTC, pyotrr commented on src/App.jsx
> +  );
nie jestem wielkim fanem trzymania dużego stanu wysoko w drzewie i przekazywania pary `state, setState`, do komponentów niżej. W 99% procentach sytuacji te komponenty niżej nie potrzebują dostępu do całej funkcjonalności `setState`. To mocno psuje czytelność. O wiele lepszym patternem byłoby zrobienie funkcji odpowiedzialnych za jakąś część funkcjonalności `setState`'a które można przekazać niżej. np
```js
const [todos, setTodos] = useState([]);
const addTodo = (todoObject) => {
  // o tej notacji niżej
  setTodos((prevTodos) => [...prevTodos, todoObject]);
}

/* ... */

return (
  <div>
    { /* ... */ }
    <FormTodo addTodo={addTodo} />
    { /* ... */ }
  </div>
);
```

od razu czytając to wiem, co będzie się działo w `<FormTodo />`

2022-11-03 11:59 UTC, pyotrr commented on src/App.jsx
> +  const [inputValue, setInputValue] = useState("");
czemu `inputValue` jest tak wysoko? tylko `<FormTodo />` go potrzebuje

2022-11-03 11:59 UTC, pyotrr commented on src/components/FormTodo.jsx
> +    if (inputValue) {
sztywniejszy check byłby bezpieczniejszy, sprawdziłbym 
```js
if (inputValue !== '')
// albo nawet
if (typeof inputValue === 'string' && inputValue)
```
szczególnie, jeśli ten stan siedzi wyżej i nie wiemy z poziomu tego kontekstu co ma do niego dostęp

2022-11-03 11:59 UTC, pyotrr commented on src/components/FormTodo.jsx
> +      setTodos([...todos, { id: nanoid(3), content: inputValue }]);
dobry instynkt do posiadania to jest pytanie siebie za każdym razem "czy potrzebuję libki". to jest niewielka rzecz, więc to nie jest tutaj problem, ale w tym miejscu jeśli chciałbym mieć unikatową wartość pewnie zrobiłbym `Date.now()`

2022-11-03 11:59 UTC, pyotrr commented on src/components/FormTodo.module.scss
> +    background: #fafbfc;
powtarzające się kolory i wgl cssowe wartości wyciągnął bym do jakiegoś innego pliku (jak najbardziej głównego) i zdefiniował na nie zmienne. np:

`index.scss`
```css
:root {
  --primaryColor: #fafbfc;
  --backgroundColor: #cecece;
}
```
i potem używać
`FormTodo.module.scss`
```css
.main {
  // ...
  input {
    background-color: var(--backgroundColor);
  }
}
```

2022-11-03 11:59 UTC, pyotrr commented on src/components/ListTodo.jsx
> +  const reversed = todos.slice().reverse();
nie wiem co to tu robi, jeśli to jest po to żeby zrobić `.reverse` na liście bez mutowania jej to lepszym sposobem byłoby
```js
const reversed = [...todos].reverse()
```

2022-11-03 11:59 UTC, pyotrr commented on src/components/ListTodo.jsx
> +  const reversed = todos.slice().reverse();
ale jeśli chodzi tylko o to żeby to było odwrotnie to chyba lepiej dodawać nowe todosy w dobrym miejscu listy

2022-11-03 11:59 UTC, pyotrr commented on src/components/ItemTodo.jsx
> +    e.stopPropagation();
co to tutaj robi?

2022-11-03 11:59 UTC, pyotrr commented on src/components/ListTodo.jsx
> +          />
tutaj dajesz zupełnie inne propsy niż `<ItemTodo />` przyjmuje

2022-11-03 11:59 UTC, pyotrr commented on src/components/FormTodo.jsx
> +      setTodos([...todos, { id: nanoid(3), content: inputValue }]);
`setState` jako argument może przyjąć 2 rzeczy
- nową wartość dla stanu
- callback, który jako argument przyjmuje obecny stan i zwraca nową wartość stanu

raczej zawsze jeśli twój nowy stan jest wyliczany na podstawie starego stanu to ta druga opcja to jest sposób w jaki powinien być używany setstate

```js
setTodos((prevTodos) => [...prevTodos, { id: nanoid(3), content: inputValue }])
```

2022-11-03 11:59 UTC, pyotrr commented
daj znać jak uda ci się poprawić te rzeczy, to będziemy myśleć co robić dalej

2022-11-04 10:58 UTC, bchronowski98 commented
zrobione

2022-11-04 11:34 UTC, pyotrr requested changes

2022-11-04 11:34 UTC, pyotrr commented on index.scss
> +  #root {
to zadziała, bo selektujesz div, który jest rodzicem wszystkich reactowych komponentów, ale chodziło mi o `:root {`

to jest pseudoelement, który ma root dokumentu, w tym przypadku element `html`, raczej taka jest konwencja
https://developer.mozilla.org/en-US/docs/Web/CSS/:root

2022-11-04 11:34 UTC, pyotrr commented on src/App.jsx
> +    setTodos(updatedTodos);
tutaj jest ta sama sytuacja, nowy stan na podstawie starego

2022-11-07 09:00 UTC, pyotrr commented on src/components/GetWeather.jsx
> +          <img src={Sunny} alt="sunny" />
SVG jako src do taga `img` trochę zabija cel SVG, powinny być użyte jako SVGElement, `<Rain />`

2022-11-07 09:01 UTC, pyotrr commented on src/components/GetWeather.module.scss
> +  }
to mi się niezbyt podoba, element nie będzie widoczny, ale cały kod odpowiedzialny za jego "tworzenie" cały czas leci

2022-11-07 10:33 UTC, pyotrr approved these changes

2022-11-07 10:33 UTC, merged