css and small changes
bchronowski98/todo-app-better pull request #7
Opened 2022-11-07 12:54 UTC by bchronowski98

2022-11-08 10:30 UTC, pyotrr requested changes

2022-11-08 10:30 UTC, pyotrr commented on src/App.module.scss
> +            fill: (var(--primaryColor));
ten nawias niepotrzebny

2022-11-08 10:30 UTC, pyotrr commented on src/components/ItemTodo.jsx
> +      editTodo(e, id, newTodo);
nie wiem, po co jest ten event przekazywany, w `editTodo` nic się z nim nie dzieje

2022-11-10 10:18 UTC, pyotrr requested changes
wciąż wydaje mi się że nie jestem w stanie oznaczyć taska jako wykonanego używając klawiatury

2022-11-14 13:44 UTC, pyotrr requested changes
z cssowych rzeczy:
nazwa taska i status nie są alignowane do środka 
![image](https://user-images.githubusercontent.com/67952400/201675177-b3d98a21-1d46-436a-9f7a-4bb940e5032b.png)

2022-11-14 13:44 UTC, pyotrr commented on src/App.jsx
>      e.preventDefault();
ten handler jest używany jako `onClick` do button, event click na buttonie nie ma żadnego defaultowego zachowania, nie można tego `e.preventDefault()` wrzucać tak do wszystkiego

2022-11-14 13:44 UTC, pyotrr commented on src/App.jsx
> +  const [editId, setEditId] = useState("");
ten stan nie musi być tak wysoko, w tym komponencie i tak nic się z nim nie dzieje

2022-11-14 13:44 UTC, pyotrr commented on src/App.jsx
> +  useOutsideClick(outsideClickRef, toggle, setToggle);
ten useOutsideClick też nie musi być tak wysoko, ref i tak jest przekazywany to innego komponentu

2022-11-14 13:44 UTC, pyotrr commented on src/components/GetWeather.jsx
> +const GetWeather = forwardRef(({ toggle, toggleWeather }, ref) => {
zmieniam zdanie, to nie musi być `forwardRef`, wszystko związane z tym refem może się odbywać w środku tego komponentu

2022-11-14 13:44 UTC, pyotrr commented on src/components/ItemTodo.jsx
> +  const ref = useRef({ refIcons, refTodoInside });
tego nie rozumiem, po co ten trzeci ref

2022-11-14 13:44 UTC, pyotrr commented on src/components/ItemTodo.jsx
> +      {isEditing && editId === id ? (
czy stan `isEditing` jest jeszcze potrzebny jeśli mamy osobny stan na `editId`. Wydaje mi się że `isEditing` zawsze równa się `Boolean(editId)`

2022-11-14 13:44 UTC, pyotrr commented on src/components/NormalTodoTemplate.jsx
> +    const { refIcons, refTodoInside } = ref.current;
to nie jest dobre wykorzystanie forwardRefa. Jedyny case kiedy forwardRef powinien być używany jest wtedy, jeśli chcesz żeby twój reactowy komponent mógł przyjmować property `ref` żeby trzymać do niego referencję. Jeśli chcesz po prostu przekazać jakieś dane, które w wyższym komponencie trzymasz w useRefie to możesz to zrobić normalnie w propsie.
```js
const myRef = useRef(null)

return (
  <Component someProp={myRef} />
)
```
chociaż to jest rzadko spotykany pattern.
Ja wciąż dość mocno uważam, że wgl trzymanie tych elementów w refie jest niepotrzebne i trochę nieeleganckie.
Problem z tym że się zaznacza task jako zrobiony jak się przez niego tabuje trzeba by rozwiązać inaczej

2022-11-14 13:44 UTC, pyotrr commented on src/hooks/useOutsideClick.jsx
> +const useOutsideClick = (ref, handler, setHandler) => {
w takiej formie jak to napisałeś to nie jest `useOutsideClick`, z nazwy takiego hooka spodziewałbym się że będę mógł odpalić jakiś callback jeśli kliknę poza podanym elementem. To co jest tutaj jest trochę bardziej specyficzne. Bardziej `useToggleOnOutsideClick`. Więc albo zrobić to bardziej ogólne, albo zmienić nazwę

2022-11-14 18:45 UTC, bchronowski98 commented on src/App.jsx
> +  const [editId, setEditId] = useState("");
ten stan jest po to, zeby kazdy task wiedzial jaki jest obecnie edytowany(jego id) i jezeli ten stan czyli editId === id danego taska to rendetuje sie Edit Template

2022-11-14 19:03 UTC, bchronowski98 commented on src/App.jsx
> +  const [editId, setEditId] = useState("");
ten stan jest po to, zeby kazdy task wiedzial jaki jest obecnie edytowany(jego id) i jezeli ten stan czyli editId === id danego taska to rendetuje sie Edit Template

2022-11-14 19:13 UTC, bchronowski98 commented on src/components/ItemTodo.jsx
> +      {isEditing && editId === id ? (
jest potrzebny, bo stan na editId zawsze bedzie to string (id poprzednio edytowanego) Bez tego edytowanie zle działa

2022-11-14 19:18 UTC, bchronowski98 commented on src/components/ItemTodo.jsx
> +  const ref = useRef({ refIcons, refTodoInside });
Chciałem te 2 refy wyżej puścić jednym refem do NormalTemplate, żeby złapać tam sobie 2 różne divy i  wykorzystac je do warunku w `onTodoClick`

2022-11-14 19:28 UTC, bchronowski98 commented on src/components/NormalTodoTemplate.jsx
> +    const { refIcons, refTodoInside } = ref.current;
Zmieniłem na ref w propsie. Myslałem trochę nad tym i nie mogłem wpaść na to jak z tym zaznaczaniem zrobić

2022-11-14 19:30 UTC, bchronowski98 commented on src/components/ItemTodo.jsx
> +  const ref = useRef({ refIcons, refTodoInside });
ale jak można refy w propsie to wszystko jasne :D

2022-11-15 10:45 UTC, pyotrr requested changes

2022-11-15 10:45 UTC, pyotrr commented on src/App.jsx
> +  const [editId, setEditId] = useState("");
tak, tak, tylko czemu on jest tutaj a nie w `<ItemTodo />`?

2022-11-15 10:45 UTC, pyotrr commented on src/components/ItemTodo.jsx
> +      {isEditing && editId === id ? (
a po co jest trzymany stan poprzedniego?

2022-11-15 10:45 UTC, pyotrr commented on src/components/NormalTodoTemplate.jsx
> +      onKeyDown={onTodoClick}
:eyes: a co jeśli keyDown to tab?

2022-11-16 09:48 UTC, merged